
from enum import Enum, unique

@unique
class TournamentStatus(Enum):
    TOURNAMENT_CREATED = 'TOURNAMENT_CREATED'
    TOURNAMENT_DELETED = 'TOURNAMENT_DELETED'
    TOURNAMENT_STARTED = 'TOURNAMENT_STARTED'
    SIGNUPS_STARTED = 'SIGNUPS_STARTED'
    PLAYER_SIGNED_UP = 'PLAYER_SIGNED_UP'
    ERROR_STATUS_CODE = 'ERROR_STATUS_CODE'
    TOURNAMENT_NOT_FOUND = 'TOURNAMENT_NOT_FOUND'


print({ TournamentStatus.ERROR_STATUS_CODE: 'id'})