from enum import Enum, unique

@unique
class TournamentStatus(Enum):
    TOURNAMENT_CREATED = 'TOURNAMENT_CREATED'
    TOURNAMENT_DELETED = 'TOURNAMENT_DELETED'
    TOURNAMENT_STARTED = 'TOURNAMENT_STARTED'
    SIGNUPS_STARTED = 'SIGNUPS_STARTED'
    PLAYER_SIGNED_UP = 'PLAYER_SIGNED_UP'
    ERROR_STATUS_CODE = 'ERROR_STATUS_CODE'
    TOURNAMENT_NOT_FOUND = 'TOURNAMENT_NOT_FOUND'
    GUILD_NOT_FOUND = 'GUILD_NOT_FOUND'
    GUILD_OR_TOURNAMENT_NOT_FOUND = 'GUILD_OR_TOURNAMENT_NOT_FOUND'

@unique
class MessageStatus(Enum):
    BOT_MESSAGE = 'BOT_MESSAGE'
    NO_ATTACHMENTS = 'NO_ATTACHMENTS'
    TOURNAMENT_OR_PLAYER_NOT_VALID = 'TOURNAMENT_OR_PLAYER_NOT_VALID'
    PLAYER_STATS_RECORDED = 'PLAYER_STATS_RECORDED'